# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=50)),
                ('project_done', models.BooleanField()),
                ('project_desc', models.CharField(blank=True, max_length=500)),
                ('project_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project_create_date', models.DateTimeField(auto_now_add=True)),
                ('project_start_date', models.DateTimeField(blank=True)),
                ('project_dead_line', models.DateTimeField(blank=True)),
                ('project_level', models.IntegerField(default=1)),
                ('project_emergence', models.CharField(choices=[('none', 'None'), ('emergency', 'Emergency'), ('wait', 'Can Wait')], default='none', max_length=10)),
                ('project_status', models.CharField(choices=[('none', 'None'), ('planning', 'Planning'), ('research', 'Researching'), ('stuck', 'Stuck'), ('doing', 'In Progress'), ('done', 'Done')], default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachments',
            fields=[
                ('project_attachment_name', models.CharField(max_length=50)),
                ('project_attachment_type', models.CharField(max_length=10)),
                ('project_attachment', models.FileField(upload_to='attachments')),
                ('project_attachment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project_attachment_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TagName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_attachment',
            field=models.ManyToManyField(blank=True, to='simplenote.ProjectAttachments'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_sub',
            field=models.ManyToManyField(blank=True, to='simplenote.SubProject'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_tag',
            field=models.ManyToManyField(blank=True, to='simplenote.TagName'),
        ),
    ]
