# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplenote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_dead_line',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
