# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplenote', '0002_auto_20171203_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
