# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTracker',
            fields=[
                ('issue_number', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_description', models.CharField(max_length=500)),
                ('issue_title', models.CharField(max_length=100)),
                ('possible_solution', models.CharField(max_length=300)),
                ('progress', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('java', models.BooleanField()),
                ('c', models.BooleanField()),
                ('cpp', models.BooleanField()),
                ('python', models.BooleanField()),
                ('sql', models.BooleanField()),
                ('cshart', models.BooleanField()),
                ('html', models.BooleanField()),
                ('javascript', models.BooleanField()),
                ('css', models.BooleanField()),
                ('r', models.BooleanField()),
                ('vbscript', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_progress', models.IntegerField()),
                ('project_description', models.CharField(max_length=300)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.IssueTracker')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_language_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Language')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('todo_number', models.IntegerField(primary_key=True, serialize=False)),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_description', models.CharField(max_length=500)),
                ('todo_progress', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='todoList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.TodoList'),
        ),
    ]
