# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='issue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.IssueTracker'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_progress',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='todoList',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.TodoList'),
        ),
    ]
