# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20171029_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='project_name',
            field=models.CharField(default='portfolio-website', max_length=30),
            preserve_default=False,
        ),
    ]
