# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_detail_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
