# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projects_project_detail_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_detail_desc',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
