# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20171110_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='project_image'),
        ),
    ]
