# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20171111_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='features',
            field=models.ManyToManyField(blank=True, to='portfolio.Features'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ManyToManyField(blank=True, to='portfolio.Project_Image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_detail_desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
